#ItemBan config file

BannedItems:
  All:
    - "§aTest Item"
  OffHand:
    - "§3スピード上昇AEX lv1"
    - "§3スピード上昇EX lv4"
    - "§3スピード上昇EX lv3"
    - "§3スピード上昇EX lv2"
    - "§3スピード上昇EX lv1"
  Armor:
    - "§aテスト§b防具"


#ReplaceItems:
#  All:
#    §aTest Item: §aTest Item2
#  OffHand:
#    §1テスト§2オフハンドアイテム: §1テスト§2オフハンドアイテム2
#  Armor:
#    §aテスト§b防具: §aテスト§b防具2