#ItemBan config file

BannedItems:
  All:
    - "§aTest Item"
  OffHand:
    - "§1テスト§2オフハンドアイテム"
  Armor:
    - "§aテスト§b防具"

ReplaceItems:
  All:
    §aTest Item: §aTest Item2
  OffHand:
    §1テスト§2オフハンドアイテム: §1テスト§2オフハンドアイテム2
  Armor:
    §aテスト§b防具: §aテスト§b防具2